language: 
  - swift

os:
  - osx

osx_image: xcode10.1

env:
  matrix:
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone 7'

script:
  - set -o pipefail
  - xcodebuild test -enableCodeCoverage YES -project RStorage.xcodeproj -scheme RStorage -sdk $TEST_SDK -destination 'platform=iOS Simulator,name=$NAME,OS=$OS' ONLY_ACTIVE_ARCH=YES | xcpretty

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode